name: Sync Notes to GitHub Pages
on:
  schedule:
    - cron: '0 * * * *' # Hourly sync (customize as needed)
  workflow_dispatch: # Allow manual triggers

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to push to GitHub Pages branch

    steps:
      - name: Checkout Notes Repo (gitbook branch)
        uses: actions/checkout@v4
        with:
          repository: Cydriin/Notes
          ref: gitbook # Your source branch
          token: ${{ secrets.SOURCE_REPO_TOKEN }}
          path: notes-content # Where source content will live

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Checkout GitHub Pages Repo (main branch)
        uses: actions/checkout@v4
        with:
          repository: Cydriin/cydriin.github.io
          ref: main # GitHub Pages branch
          token: ${{ secrets.SOURCE_REPO_TOKEN }}
          path: github-pages # Where GitHub Pages content lives

      - name: Copy Notes Content to GitHub Pages
        run: |
          # Delete existing content in GitHub Pages repo (except .git)
          find github-pages -mindepth 1 -maxdepth 1 -not -name '.git' -exec rm -rf {} +
          
          # Copy everything from Notes repo's gitbook branch
          cp -r notes-content/. github-pages/

          # Optional: Remove Obsidian-specific files
          # rm -rf github-pages/.obsidian/

      - name: Commit and Push Changes
        run: |
          cd github-pages
          git add .
          git commit -m "Auto-sync: $(date +'%Y-%m-%d %H:%M:%S')" || echo "No changes to commit"
          git push origin main # Push to GitHub Pages repo's main branch
